-- Create comprehensive SEO database tables (Simplified version without RLS)
-- This migration creates all necessary tables for full SEO Configuration functionality

-- 1. SEO Events Table (for tracking user interactions and SEO events)
CREATE TABLE IF NOT EXISTS seo_events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  event VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL,
  action VARCHAR(100) NOT NULL,
  label VARCHAR(255),
  value DECIMAL(10,2),
  custom_parameters JSONB DEFAULT '{}',
  url TEXT,
  user_agent TEXT,
  referrer TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. SEO Monitoring Data Table (for storing real-time SEO metrics)
CREATE TABLE IF NOT EXISTS seo_monitoring_data (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  url TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Page Metrics
  page_views INTEGER DEFAULT 0,
  unique_visitors INTEGER DEFAULT 0,
  bounce_rate DECIMAL(5,2) DEFAULT 0,
  average_session_duration DECIMAL(10,2) DEFAULT 0,
  organic_traffic INTEGER DEFAULT 0,
  
  -- SEO Metrics
  backlinks INTEGER DEFAULT 0,
  domain_authority INTEGER DEFAULT 0,
  indexed_pages INTEGER DEFAULT 0,
  crawl_errors INTEGER DEFAULT 0,
  
  -- Performance Metrics
  page_speed_mobile INTEGER DEFAULT 0,
  page_speed_desktop INTEGER DEFAULT 0,
  lcp DECIMAL(10,2) DEFAULT 0, -- Largest Contentful Paint
  fid DECIMAL(10,2) DEFAULT 0, -- First Input Delay
  cls DECIMAL(10,2) DEFAULT 0, -- Cumulative Layout Shift
  fcp DECIMAL(10,2) DEFAULT 0, -- First Contentful Paint
  ttfb DECIMAL(10,2) DEFAULT 0, -- Time to First Byte
  
  -- Additional Data
  keyword_rankings JSONB DEFAULT '[]',
  issues JSONB DEFAULT '[]',
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. SEO Reports Table (for storing generated SEO reports)
CREATE TABLE IF NOT EXISTS seo_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  report_type VARCHAR(50) NOT NULL, -- 'audit', 'performance', 'analytics', 'monitoring'
  period_start TIMESTAMP WITH TIME ZONE NOT NULL,
  period_end TIMESTAMP WITH TIME ZONE NOT NULL,
  url TEXT,
  
  -- Report Data
  overall_score INTEGER DEFAULT 0,
  total_issues INTEGER DEFAULT 0,
  critical_issues INTEGER DEFAULT 0,
  warnings INTEGER DEFAULT 0,
  recommendations JSONB DEFAULT '[]',
  metrics JSONB DEFAULT '{}',
  issues JSONB DEFAULT '[]',
  
  -- Status
  status VARCHAR(20) DEFAULT 'completed', -- 'pending', 'processing', 'completed', 'failed'
  generated_by UUID, -- user_id if generated by user
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. SEO Audit Results Table (for storing detailed audit results)
CREATE TABLE IF NOT EXISTS seo_audit_results (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  url TEXT NOT NULL,
  audit_type VARCHAR(50) NOT NULL, -- 'technical', 'content', 'performance', 'mobile'
  
  -- Audit Results
  score INTEGER DEFAULT 0,
  total_checks INTEGER DEFAULT 0,
  passed_checks INTEGER DEFAULT 0,
  failed_checks INTEGER DEFAULT 0,
  warnings INTEGER DEFAULT 0,
  
  -- Detailed Results
  issues JSONB DEFAULT '[]',
  recommendations JSONB DEFAULT '[]',
  technical_details JSONB DEFAULT '{}',
  
  -- Metadata
  audit_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  audit_duration INTEGER DEFAULT 0, -- in milliseconds
  user_agent TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. SEO Keyword Rankings Table (for tracking keyword positions)
CREATE TABLE IF NOT EXISTS seo_keyword_rankings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  keyword VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  search_engine VARCHAR(50) DEFAULT 'google',
  position INTEGER,
  search_volume INTEGER DEFAULT 0,
  difficulty DECIMAL(5,2) DEFAULT 0,
  cpc DECIMAL(10,2) DEFAULT 0,
  competition VARCHAR(20) DEFAULT 'medium', -- 'low', 'medium', 'high'
  
  -- Tracking Data
  date DATE NOT NULL,
  previous_position INTEGER,
  position_change INTEGER DEFAULT 0,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. SEO Alerts Table (for monitoring alerts and notifications)
CREATE TABLE IF NOT EXISTS seo_alerts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  alert_type VARCHAR(50) NOT NULL, -- 'performance', 'ranking', 'error', 'warning'
  severity VARCHAR(20) NOT NULL, -- 'low', 'medium', 'high', 'critical'
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  url TEXT,
  
  -- Alert Data
  threshold_value DECIMAL(10,2),
  current_value DECIMAL(10,2),
  metric_name VARCHAR(100),
  
  -- Status
  status VARCHAR(20) DEFAULT 'active', -- 'active', 'acknowledged', 'resolved', 'dismissed'
  acknowledged_by UUID, -- user_id
  acknowledged_at TIMESTAMP WITH TIME ZONE,
  resolved_at TIMESTAMP WITH TIME ZONE,
  
  -- Notification
  email_sent BOOLEAN DEFAULT false,
  email_sent_at TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. SEO Settings Table (for advanced SEO configuration)
CREATE TABLE IF NOT EXISTS seo_settings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value TEXT,
  setting_type VARCHAR(20) DEFAULT 'string', -- 'string', 'number', 'boolean', 'json'
  category VARCHAR(50) DEFAULT 'general', -- 'analytics', 'monitoring', 'performance', 'social'
  description TEXT,
  is_public BOOLEAN DEFAULT false, -- whether setting can be accessed publicly
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. SEO Test Results Table (for storing SEO test results)
CREATE TABLE IF NOT EXISTS seo_test_results (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  test_type VARCHAR(50) NOT NULL, -- 'rich-results', 'pagespeed', 'mobile-friendly', 'structured-data', 'meta-tags', 'web-vitals'
  url TEXT NOT NULL,
  
  -- Test Results
  success BOOLEAN DEFAULT false,
  score INTEGER,
  message TEXT,
  details JSONB DEFAULT '{}',
  result_data JSONB DEFAULT '{}',
  
  -- Test Metadata
  test_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  test_duration INTEGER DEFAULT 0, -- in milliseconds
  user_agent TEXT,
  api_response_time INTEGER DEFAULT 0,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_seo_events_timestamp ON seo_events(timestamp);
CREATE INDEX IF NOT EXISTS idx_seo_events_category ON seo_events(category);
CREATE INDEX IF NOT EXISTS idx_seo_events_url ON seo_events(url);

CREATE INDEX IF NOT EXISTS idx_seo_monitoring_url ON seo_monitoring_data(url);
CREATE INDEX IF NOT EXISTS idx_seo_monitoring_timestamp ON seo_monitoring_data(timestamp);

CREATE INDEX IF NOT EXISTS idx_seo_reports_type ON seo_reports(report_type);
CREATE INDEX IF NOT EXISTS idx_seo_reports_period ON seo_reports(period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_seo_reports_url ON seo_reports(url);

CREATE INDEX IF NOT EXISTS idx_seo_audit_url ON seo_audit_results(url);
CREATE INDEX IF NOT EXISTS idx_seo_audit_type ON seo_audit_results(audit_type);
CREATE INDEX IF NOT EXISTS idx_seo_audit_timestamp ON seo_audit_results(audit_timestamp);

CREATE INDEX IF NOT EXISTS idx_seo_keywords_keyword ON seo_keyword_rankings(keyword);
CREATE INDEX IF NOT EXISTS idx_seo_keywords_url ON seo_keyword_rankings(url);
CREATE INDEX IF NOT EXISTS idx_seo_keywords_date ON seo_keyword_rankings(date);

CREATE INDEX IF NOT EXISTS idx_seo_alerts_type ON seo_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_seo_alerts_severity ON seo_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_seo_alerts_status ON seo_alerts(status);
CREATE INDEX IF NOT EXISTS idx_seo_alerts_created ON seo_alerts(created_at);

CREATE INDEX IF NOT EXISTS idx_seo_settings_key ON seo_settings(setting_key);
CREATE INDEX IF NOT EXISTS idx_seo_settings_category ON seo_settings(category);

CREATE INDEX IF NOT EXISTS idx_seo_test_type ON seo_test_results(test_type);
CREATE INDEX IF NOT EXISTS idx_seo_test_url ON seo_test_results(url);
CREATE INDEX IF NOT EXISTS idx_seo_test_timestamp ON seo_test_results(test_timestamp);

-- Insert default SEO settings
INSERT INTO seo_settings (setting_key, setting_value, setting_type, category, description, is_public) VALUES
('enable_seo_monitoring', 'true', 'boolean', 'monitoring', 'Enable real-time SEO monitoring', false),
('monitoring_interval', '3600', 'number', 'monitoring', 'SEO monitoring interval in seconds', false),
('enable_seo_alerts', 'true', 'boolean', 'monitoring', 'Enable SEO alerts and notifications', false),
('alert_email', '', 'string', 'monitoring', 'Email address for SEO alerts', false),
('performance_threshold_lcp', '2.5', 'number', 'performance', 'LCP threshold for alerts (seconds)', false),
('performance_threshold_cls', '0.1', 'number', 'performance', 'CLS threshold for alerts', false),
('performance_threshold_fid', '100', 'number', 'performance', 'FID threshold for alerts (milliseconds)', false),
('enable_keyword_tracking', 'true', 'boolean', 'analytics', 'Enable keyword ranking tracking', false),
('keyword_tracking_interval', '86400', 'number', 'analytics', 'Keyword tracking interval in seconds', false),
('enable_structured_data_validation', 'true', 'boolean', 'structured-data', 'Enable automatic structured data validation', false),
('enable_meta_tags_validation', 'true', 'boolean', 'content', 'Enable automatic meta tags validation', false),
('enable_core_web_vitals_tracking', 'true', 'boolean', 'performance', 'Enable Core Web Vitals tracking', true),
('enable_seo_analytics', 'true', 'boolean', 'analytics', 'Enable SEO analytics tracking', true)
ON CONFLICT (setting_key) DO NOTHING;

-- Add comments to tables
COMMENT ON TABLE seo_events IS 'Stores SEO tracking events and user interactions';
COMMENT ON TABLE seo_monitoring_data IS 'Stores real-time SEO monitoring metrics and performance data';
COMMENT ON TABLE seo_reports IS 'Stores generated SEO reports and analysis results';
COMMENT ON TABLE seo_audit_results IS 'Stores detailed SEO audit results and recommendations';
COMMENT ON TABLE seo_keyword_rankings IS 'Tracks keyword rankings across different search engines';
COMMENT ON TABLE seo_alerts IS 'Stores SEO alerts and monitoring notifications';
COMMENT ON TABLE seo_settings IS 'Stores advanced SEO configuration settings';
COMMENT ON TABLE seo_test_results IS 'Stores results from various SEO testing tools';
