import {
  Star,
  Rocket,
  Home,
  KeyRound,
  Eye,
  Baby,
  Building2,
  Tag,
  Diamond,
  Users,
  Flower2,
  HandCoins,
  DoorOpen,
  ArrowUpRight,
  CalendarCheck,
  PawPrint,
  Trees,
  Waves,
  Building
} from 'lucide-react'

export const CATEGORY_LIST = [
  { label: 'Trending', icon: Star },
  { label: 'Endless Sea Views', icon: Waves },
  { label: 'Resale Homes', icon: Home },
  { label: 'New Launch', icon: Rocket },
  { label: 'Gated Communities', icon: DoorOpen },
  { label: 'By Invite Only', icon: KeyRound },
  { label: 'Pet Paradise', icon: PawPrint },
  { label: 'Large Gardens', icon: Trees },
  { label: 'Childhood Galore', icon: Baby },
  { label: 'Huge Balconies', icon: Building2 },
  { label: 'Exclusive Deals', icon: Tag },
  { label: '1 Home Per Floor', icon: Building },
  { label: 'Ready Today', icon: CalendarCheck },
  { label: 'Panoramic Views', icon: Eye },
  { label: '5 Star Pools', icon: Flower2 },
  { label: 'Last Chance', icon: ArrowUpRight },
  { label: 'Jodi Options', icon: Users },
  { label: 'Rare Payment Plan', icon: HandCoins },
  { label: 'Diamond Living', icon: Diamond },
] as const 