import {
  Star,
  Rocket,
  Home,
  KeyRound,
  Eye,
  Gift,
  Heart,
  Leaf,
  Baby,
  Building2,
  Tag,
  Diamond,
  Sun,
  Users,
  Flower2,
  HandCoins,
  DoorOpen,
  Layers,
  ArrowUpRight,
  ArrowDownLeft,
  CalendarCheck,
  Coins,
  ArrowRight,
  ArrowLeft,
  PawPrint,
  Smile,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  User,
  BedDouble,
  Bath,
  Trees,
  Waves,
  MapPin,
  Lock,
  Unlock,
  Building,
  BuildingIcon,
  Building2Icon,
  Home as Building3,
  Building2 as Building4,
  Building as Building5,
  Home as Building6,
  Building2 as Building7,
  Building as Building8,
  Home as Building9,
  Building2 as Building10,
  Building as Building11,
  Home as Building12,
  Building2 as Building13,
  Building as Building14,
  Home as Building15,
  Building2 as Building16,
  Building as Building17,
  Home as Building18,
  Building2 as Building19,
  Building as Building20,
  Home as Building21,
  Building2 as Building22,
  Building as Building23,
  Home as Building24,
  Building2 as Building25,
  Building as Building26,
  Home as Building27,
  Building2 as Building28,
  Building as Building29,
  Home as Building30,
  Building2 as Building31,
  Building as Building32,
  Home as Building33,
  Building2 as Building34,
  Building as Building35,
  Home as Building36,
  Building2 as Building37,
  Building as Building38,
  Home as Building39,
  Building2 as Building40,
  Building as Building41,
  Home as Building42,
  Building2 as Building43,
  Building as Building44,
  Home as Building45,
  Building2 as Building46,
  Building as Building47,
  Home as Building48,
  Building2 as Building49,
  Building as Building50
} from 'lucide-react'

export const CATEGORY_LIST = [
  { label: 'Trending', icon: Star },
  { label: 'Endless Sea Views', icon: Waves },
  { label: 'Resale Homes', icon: Home },
  { label: 'New Launch', icon: Rocket },
  { label: 'Gated Communities', icon: DoorOpen },
  { label: 'By Invite Only', icon: KeyRound },
  { label: 'Pet Paradise', icon: PawPrint },
  { label: 'Large Gardens', icon: Trees },
  { label: 'Childhood Galore', icon: Baby },
  { label: 'Huge Balconies', icon: Building2 },
  { label: 'Exclusive Deals', icon: Tag },
  { label: '1 Home Per Floor', icon: Building },
  { label: 'Ready Today', icon: CalendarCheck },
  { label: 'Panoramic Views', icon: Eye },
  { label: '5 Star Pools', icon: Flower2 },
  { label: 'Last Chance', icon: ArrowUpRight },
  { label: 'Jodi Options', icon: Users },
  { label: 'Rare Payment Plan', icon: HandCoins },
  { label: 'Diamond Living', icon: Diamond },
] as const 